const axios = require('axios');

/**
 * Generates content using Google Gemini API
 * @param {string} prompt - The user's prompt
 * @param {string} systemInstruction - Optional system instruction
 * @returns {Promise<string>} - Generated content
 */
const generateContent = async (prompt, systemInstruction = '') => {
  try {
    // In a real implementation, you would use the actual Google Gemini API
    // This is a mock implementation for demonstration purposes
    
    // Example of how you would call the real API:
    /*
    const API_KEY = process.env.GEMINI_API_KEY;
    const MODEL_NAME = 'gemini-2.5-flash-preview-09-2025';
    
    const requestBody = {
      contents: [{
        parts: [{
          text: prompt
        }]
      }]
    };
    
    if (systemInstruction) {
      requestBody.systemInstruction = {
        parts: [{
          text: systemInstruction
        }]
      };
    }
    
    const response = await axios.post(
      `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${API_KEY}`,
      requestBody,
      {
        headers: {
          'Content-Type': 'application/json'
        }
      }
    );
    
    return response.data.candidates[0].content.parts[0].text;
    */
    
    // Mock implementation for demonstration
    // In a real app, remove this and use the actual API call above
    return `This is a mock AI-generated response based on your prompt: "${prompt}". In a real implementation, this would be generated by Google Gemini API with the system instruction: "${systemInstruction || 'None provided'}".`;
  } catch (error) {
    console.error('AI content generation error:', error);
    throw new Error('Failed to generate content using AI service');
  }
};

module.exports = { generateContent };